name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-aspect_macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: aspect_macro

      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
        working-directory: aspect_macro

      - name: Check code format for aspect_macro
        run: cargo fmt --all -- --check
        working-directory: aspect_macro

      - name: Build and check aspect_macro
        run: cargo build --all
        working-directory: aspect_macro

  build-builder_macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: builder_macro

      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
        working-directory: builder_macro

      - name: Check code format for builder_macro
        run: cargo fmt --all -- --check
        working-directory: builder_macro

      - name: Build and check builder_macro
        run: cargo build --all
        working-directory: builder_macro

  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: project

      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
        working-directory: project

      - name: Check code format for project
        run: cargo fmt --all -- --check
        working-directory: project

      - name: Build and check project
        run: cargo build --all
        working-directory: project